# title: "Adithi Satish's Website"
author: "Adithi Satish"
description: "Profile"
baseurl: "" # Leave blank for user GitHub Pages
url: "https://adithisatish.github.io" # Your GitHub Pages URL

# Theme selection
theme: minima

# Social links (optional)
twitter_username: spillingaditea
github_username: adithisatish
linkedin_username: adithisatish
email: adithi.satish@tum.de

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - publications.md
